Knihovna/Areas/Admin/Controllers/OptionsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using DataAccess.Dao;
using DataAccess.Model;
using Systems = DataAccess.Model.Systems;

namespace Knihovna.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OptionsController : Controller
    {
        // GET: Admin/Options
        public ActionResult Index()
        {

            CodeDao codeDao = new CodeDao();
            IList<Code> code = codeDao.GetAll();
            ViewBag.Code = code;

            SystemsDao sysDao = new SystemsDao();

            IList<Systems> sys = sysDao.GetByMarker(10);
            return View(sys);
        }

        public ActionResult Pohled(int id)
        {
            SystemsDao sysDao = new SystemsDao();
            Systems sys = sysDao.GetById(id);

            return View(sys);
        }


        
        public ActionResult UpdateO(Systems systems, HttpPostedFileBase obr1)
        {
            SystemsDao sysDao = new SystemsDao();
            Systems sys = sysDao.GetById(systems.Id);

            try
            {
                if (obr1 != null)
                {
                    if (obr1.ContentType == "image/jpeg" || obr1.ContentType == "image/png")
                    {
                        Image image = Image.FromStream(obr1.InputStream);
                        Guid guid = Guid.NewGuid();
                        string imageName = guid.ToString() + ".jpg";
                        obr1.SaveAs(Server.MapPath("~/img/" + imageName));
                        System.IO.File.Delete(Server.MapPath("~/img/" + sys.Value));
                        systems.Value = imageName;
                    }
                }
                sysDao.Merge(systems);
                TempData["message-success"] = "Záznam byl upraven";
            }
            catch (Exception)
            {
                throw;
            }
          
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int id)
        {
            try
            {
                CodeDao codeDao = new CodeDao();
                Code code = codeDao.GetById(id);

                codeDao.Delete(code);
                TempData["message-success"] = "Kód byl smazán";
            }
            catch (Exception)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        public ActionResult AddCode()
        {
            CodeDao codeDao = new CodeDao();



            Code code = new Code();
            code.Scode = Guid.NewGuid().ToString();

            codeDao.Create(code);


            return RedirectToAction("Index");
        }




    }
}

Knihovna/Areas/Admin/Views/Options/Index.cshtml
@using DataAccess.Model
@model IList<DataAccess.Model.Systems>
@{
    ViewBag.Title = "Index";
}

<h2>Nastavení carouselu</h2>


@foreach (Systems s in Model)
{

    Html.RenderAction("Pohled", new { s.Id });
}



<div class="container-fluid">
    <div class="row">
        <div class="col-lg-5">

            <h2>Generování VIP kódu</h2>

        </div>

        <div class="col-lg-2">
            
            <a href="@Url.Action("AddCode")" class="btn btn-primary">Vytvořit nový VIP kód</a>

        </div>

    </div>
</div>


<table class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>Code ID</th>
        <th>Code</th>
        <th>Akce</th>

        

    </tr>
    </thead>
    <tbody>

    @foreach (Code b in ViewBag.Code)
    {
        <tr>

            <td>@b.Id</td>
            <td>@b.Scode</td>
            <td>@Html.ActionLink("Smazání", "Delete", "Options", new { id = b.Id }, new { onclick = "return confirm('Přejete si opravdu kód smazat?');" })
            </td>

         
        </tr>
    }



    </tbody>
</table>

Knihovna/Areas/Admin/Views/Options/Pohled.cshtml
@model DataAccess.Model.Systems
@{
    ViewBag.Title = "Index";
    Layout = null;
}

@Html.ValidationSummary()

@using (Html.BeginForm("UpdateO", "Options", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{
   @Html.HiddenFor(x => x.Id)
   @Html.HiddenFor(x => x.Marker)
    @Html.HiddenFor(x => x.Value)




    <div class="container">
        <div class="row">
            <div class="col-lg-4">
         
                <div class="form-group">
                    <label class="control-label">Popis k foto @Model.Id:</label>
                    <div class="col-sm-10">

                        @Html.TextAreaFor(x => x.Description, new { @class = "form-control", rows = 5})

                    </div>
                </div>      
            </div> <div class="col-lg-6">
                
                <div class="form-group">
                    <label class="control-label">Obrazek @Model.Id:</label>
                    <div class="col-sm-10">

                        <input name="obr1" type="file"/>
            
                        @if(!string.IsNullOrEmpty(Model.Value))
                        {
                            <img src="@Url.Content("~/img/" + Model.Value)"/>
                        }
                    </div>
                </div>              
            </div> 
            <div class="col-lg-2">

                <div class="form-group">
                    <div class="m-5">
                        <button type="submit" class="btn btn-primary" onclick="return confirm('Přejete si opravdu provést změny?')">Potvrdit</button>
                    </div>
                </div>

            </div>

        </div>
    </div>
    <hr>

    
}