Knihovna/Areas/Admin/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Dao;
using DataAccess.Model;

namespace Knihovna.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GalleryController : Controller
    {
        // GET: Admin/Gallery
        public ActionResult Index()
        {
            return RedirectToAction("Automobil");
        }

        public ActionResult Automobil()
        {
            ImageAutoDao imageDao = new ImageAutoDao();
            IList<ImageAuto> imageAuto = imageDao.GetAll();



            return View(imageAuto);
            
        }




        public ActionResult Delete(int id)
        {
            try
            {
                ImageAutoDao imageDao = new ImageAutoDao();
                ImageAuto imageAuto = imageDao.GetById(id);

                imageDao.Delete(imageAuto);
                TempData["message-success"] = "Fotografie byla smazána";

            }
            catch (Exception)
            {
                throw;
            }

            return RedirectToAction("Automobil");

        }

        public ActionResult Add()
        {
            ViewBag.Auto = new AutoDao().GetAll();
            ImageAuto image = new ImageAuto();

            if (Request.IsAjaxRequest())
            {

                return PartialView(image);
            }

            return View(image);

        }




        public ActionResult Update(ImageAuto image, HttpPostedFileBase img)
        {

            ImageAutoDao imageDao = new ImageAutoDao();

            if (img != null)
            {
                if (img.ContentType == "image/jpeg" || img.ContentType == "image/png")
                {
                    Guid gu = Guid.NewGuid();
                    string imageName = gu.ToString() + ".jpg";
                    img.SaveAs(Server.MapPath("~/img/img_cars/" + imageName));
                    image.ImageName = imageName;
                    imageDao.Create(image);

                }
            }


            return RedirectToAction("Automobil");
        }

        public ActionResult SearchCar(string phrase)
        {


            AutoDao autoDao = new AutoDao();
            IList<Auto> auta = autoDao.SearchCars(phrase);


            ImageAutoDao imageDao = new ImageAutoDao();

            IList<ImageAuto> imageAuto = new List<ImageAuto>();

            foreach (var c in auta)
            {
                IList<ImageAuto> im = new List<ImageAuto>();
                im = imageDao.ImageAuto(c.Id);
                foreach (var images in im)
                {
                    imageAuto.Add(images);
                }


            }


            return View("Automobil", imageAuto);

        }

    }
}

Knihovna/Areas/Admin/Views/Gallery/Add.cshtml
@using DataAccess.Model
@model ImageAuto

@{
    ViewBag.Title = "Edit";
}

@Html.ValidationSummary()

@using (Html.BeginForm("Update", "Gallery", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(Id => Model.Id)

    <div class="form-group">
        <label class="control-label col-sm-2">Fotografie:</label>
        <div class="col-sm-10">
            <input type="file" name="img" />

        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Automobil:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x => x.Auto.Id, new SelectList(ViewBag.Auto, "Id", "ModelAZnacka"), new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Automobil:</label>
        <div class="col-sm-10">

            @Html.CheckBoxFor(x => x.SIsFirst)       
        
            </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary" onclick="return confirm('Přejete si opravdu provést změny?')">Potvrdit</button>
        </div>
    </div>


}

Knihovna/Areas/Admin/Views/Gallery/Automobil.cshtml
@using DataAccess.Model
@model IList<ImageAuto>
@{
    ViewBag.Title = "title";
}


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">

            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>



<div class="container">
    <div class="row">
        <div class="col-lg-9">
            <h2>Fotografie automobilů</h2>
        </div>
        <div class="col-lg-3">
            @Ajax.ActionLink("Nová fotografie", "Add", new { }, new AjaxOptions() { UpdateTargetId = "modalContent", InsertionMode = InsertionMode.Replace, OnBegin = "openModalWindow" }, new { @class = "btn btn-primary container" })
            
            <div class="mt-2"></div>
            
            @using (Html.BeginForm("SearchCar", "Gallery", FormMethod.Post, new { @class = "nav-item" }))
            {

                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control" placeholder="Vyhledat auto" name="phrase" id="searchBox" />
                        <span class="mx-2">
                            <input type="submit" value="Hledat" class="btn btn-primary my-2 my-sm-0" />

                        </span>
                    </div>
                </div>

            }
            
            

        </div>
    </div>
</div>

<table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Fotografie</th>
            <th>Id fotografie</th>
            <th>Automobil</th>
            <th>ID automobilu</th>
            <th>Akce</th>



        </tr>
    </thead>
    <tbody>

        @foreach (ImageAuto b in Model)
        {
            <tr @(b.SIsFirst == true ? "style=background-color:bisque" : "")>

                <td>
                    @if (!string.IsNullOrEmpty(b.ImageName))
                    {
                        <img src="@Url.Content("~/img/img_cars/" + b.ImageName)" width="300px" />

                    }

                </td>

                <td><a href="#">@b.Id</a></td>

                <td>@b.Auto.ModelAZnacka</td>
                <td>@b.Auto.Id</td>

                <td>
                    @Html.ActionLink("Smazání", "Delete", "Gallery", new { id = b.Id }, new { onclick = "return confirm('prejete si opravdu knihu smazat?');" })

                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    function openModalWindow() {
        $('#myModal').modal({
            show: true
        });
    }
</script>