Knihovna/Areas/Admin/Controllers/DatabaseController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Dao;
using DataAccess.Model;
using Region = DataAccess.Model.Region;

namespace Knihovna.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DatabaseController : Controller
    {
        // GET: Admin/Database
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Objednavky()
        {
            ObjednavkaDao objednavkaDao = new ObjednavkaDao();
            IList<Objednavka> objednavka = objednavkaDao.GetAll();

            return View(objednavka);
        }
        public ActionResult Testovaci()
        {
            TestovaciJizdaDao testovaciDao = new TestovaciJizdaDao();
            IList<TestovaciJizda> testovaci = testovaciDao.GetAll();

            return View(testovaci);
        }
        public ActionResult Pobocky()
        {
            PobockaDao pobockaDao = new PobockaDao();
            IList<Pobocka> pobocka = pobockaDao.GetAll();

            return View(pobocka);
        }
        public ActionResult Zakaznici()
        {
            ZakaznikDao zakaznikDao = new ZakaznikDao();
            IList<Zakaznik> zakaznik = zakaznikDao.GetAll();


            return View(zakaznik);
        }
        public ActionResult Auta()
        {
            AutoDao autoDao = new AutoDao();
            IList<Auto> auto = autoDao.GetAll();

            ImageAutoDao imageDao = new ImageAutoDao();

            return View(auto);
        }

        public ActionResult Prislusenstvi()
        {

            PrislusenstviDao Dao = new PrislusenstviDao();
            IList<Prislusenstvi> prislusenstvi = Dao.GetAll();

            return View(prislusenstvi);
        }

        public ActionResult ImageRender(int id)
        {

            ImageAutoDao imageAutoDao = new ImageAutoDao();

            IList<ImageAuto> imageAuto = imageAutoDao.HeadImageAuto(id);

            if (imageAuto.Count == 0)
            {
                imageAuto = imageAutoDao.HeadImageAuto(1);
            }

            return View(imageAuto);
        }



        //Objednavka Controllers
        public ActionResult EditO(int id)
        {
            ObjednavkaDao Dao = new ObjednavkaDao();
            Objednavka objednavka = Dao.GetById(id);

            ZamestnanecDao zamestnanecDao = new ZamestnanecDao();
            ZakaznikDao zakaznikDao = new ZakaznikDao();
            PrislusenstviDao prislusenstviDao = new PrislusenstviDao();
            AutoDao autoDao = new AutoDao();



            ViewBag.Zam = zamestnanecDao.GetAll();
            ViewBag.Zak = zakaznikDao.GetAll();
            ViewBag.Pri = prislusenstviDao.GetAll();
            ViewBag.Auto = autoDao.GetAll();

            if (Request.IsAjaxRequest())
            {
                return PartialView(objednavka);

            }

            return View(objednavka);
        }

        public ActionResult DeleteO(int id)
        {
            try
            {
                ObjednavkaDao Dao = new ObjednavkaDao();
                Objednavka objednavka = Dao.GetById(id);
                Dao.Delete(objednavka);
                TempData["message-success"] = "Položka byla smazana";
            }
            catch (Exception exception)
            {
                throw;
            }
            return RedirectToAction("Objednavky");
        }

        [HttpPost]
        public ActionResult UpdateO(Objednavka objednavka)
        {

            try
            {
                ObjednavkaDao objednavkaDao = new ObjednavkaDao();


                objednavkaDao.Update(objednavka);

                TempData["message-success"] = "Objednávka byla upravena";
            }
            catch (Exception)
            {
                throw;

            }

            return RedirectToAction("Objednavky");
        }

        public ActionResult DetailO(int id)
        {
            ObjednavkaDao objednavkaDao = new ObjednavkaDao();
            Objednavka objednavka = objednavkaDao.GetById(id);

            return PartialView(objednavka);
        }
        //------------------------------


        //TODO
        // Testovaci jizdy controller
        public ActionResult EditT(int id)

        {

            AutoDao autDao = new AutoDao();
            ZakaznikRegistrovanyDao regDao = new ZakaznikRegistrovanyDao();
            ZamestnanecDao zamDao = new ZamestnanecDao();


            ViewBag.Zam = zamDao.GetAll();
            ViewBag.Reg = regDao.GetAll();
            ViewBag.Aut = autDao.GetAll();


            TestovaciJizdaDao Dao = new TestovaciJizdaDao();
            TestovaciJizda testovaci = Dao.GetById(id);

            if (Request.IsAjaxRequest())
            {
                return PartialView(testovaci);
            }



            return View(testovaci);
        }

        public ActionResult DeleteT(int id)
        {
            try
            {
                TestovaciJizdaDao Dao = new TestovaciJizdaDao();
                TestovaciJizda testovaci = Dao.GetById(id);
                Dao.Delete(testovaci);
                TempData["message-success"] = "Položka byla smazana";
            }
            catch (Exception exception)
            {
                throw;
            }
            return RedirectToAction("Testovaci");
        }

        [HttpPost]
        public ActionResult UpdateT(TestovaciJizda jizda)
        {

            try
            {
                TestovaciJizdaDao Dao = new TestovaciJizdaDao();

                Dao.Update(jizda);

                TempData["message-success"] = "Jízda byla upravena";
            }
            catch (Exception)
            {
                throw;

            }

            return RedirectToAction("Testovaci");
        }

        public ActionResult DetailT(int id)
        {
            TestovaciJizdaDao Dao = new TestovaciJizdaDao();
            TestovaciJizda testovaci = Dao.GetById(id);
            if (Request.IsAjaxRequest())
            {
                return PartialView(testovaci);

            }

            return View(testovaci);
        }
        //------------------------------

        //TODO
        //  prehled pobocek controller
        public ActionResult EditP(int id)
        {

            PobockaDao Dao = new PobockaDao();
            Pobocka pobocka = Dao.GetById(id);


            RegionDao regionDao = new RegionDao();
            ViewBag.Region = regionDao.GetAll();


            if (Request.IsAjaxRequest())
            {
                return PartialView(pobocka);

            }

            return View(pobocka);
        }

        public ActionResult DeleteP(int id)
        {
            try
            {
                PobockaDao Dao = new PobockaDao();
                Pobocka pobocka = Dao.GetById(id);

                Dao.Delete(pobocka);
                TempData["message-success"] = "Položka byla smazana";
            }
            catch (Exception exception)
            {
                throw;
            }
            return RedirectToAction("Pobocky");
        }

        [HttpPost]
        public ActionResult UpdateP(Pobocka pobocka)
        {

            try
            {
                PobockaDao pobockaDao = new PobockaDao();


                pobockaDao.Update(pobocka);

                TempData["message-success"] = "Pobočka byla upravena";
            }
            catch (Exception)
            {
                throw;

            }

            return RedirectToAction("Pobocky");
        }

        public ActionResult DetailP(int id)
        {
            PobockaDao Dao = new PobockaDao();
            Pobocka pobocka = Dao.GetById(id);
            if (Request.IsAjaxRequest())
            {
                return PartialView(pobocka);
            }
            return View(pobocka);
        }




        public ActionResult AddP()
        {
            Pobocka pobocka = new Pobocka();
            RegionDao regionDao = new RegionDao();
            IList<Region> region = regionDao.GetAll();
            ViewBag.Region = region;

            if (Request.IsAjaxRequest())
            {
                return PartialView(pobocka);
            }

            return View(pobocka);
        }

        public ActionResult AddPobocka(Pobocka pobocka)
        {
            try
            {
                PobockaDao Dao = new PobockaDao();
                Dao.Create(pobocka);

            }
            catch (Exception)
            {
                throw;
            }


            return RedirectToAction("Pobocky");
        }

        //------------------------------


        // Zakaznici controller
        public ActionResult EditZ(int id)
        {
            ZakaznikDao zakaznikDao = new ZakaznikDao();
            Zakaznik zakaznik = zakaznikDao.GetById(id);

            OpravneniDao opravneni = new OpravneniDao();
            ViewBag.Opravneni = opravneni.GetAll();
            if (Request.IsAjaxRequest())
            {
                return PartialView(zakaznik);

            }

            return View(zakaznik);
        }

        public ActionResult DeleteZ(int id)
        {
            try
            {
                ZakaznikDao Dao = new ZakaznikDao();
                Zakaznik zakaznik = Dao.GetById(id);

                Dao.Delete(zakaznik);
                TempData["message-success"] = "Položka byla smazana";
            }
            catch (Exception exception)
            {
                throw;
            }
            return RedirectToAction("Zakaznici");
        }

        [HttpPost]
        public ActionResult UpdateZ(Zakaznik zakaznik)
        {

            try
            {

                ZakaznikDao zakaznikDao = new ZakaznikDao();

                zakaznikDao.Update(zakaznik);

                TempData["message-success"] = "Zákazník byl upraven";
            }
            catch (Exception)
            {

Knihovna/Areas/Admin/Views/Database/AddA.cshtml
@using System.Collections
@using DataAccess.Model
@model DataAccess.Model.Auto
@{
    IList<string> barvy = new List<string>();
    barvy.Add("Zluta");
    barvy.Add("Modra");
    barvy.Add("Bila");
    barvy.Add("Cervena");
    barvy.Add("Zelena");
    barvy.Add("Seda");
    barvy.Add("Cerna");
    barvy.Add("Hneda");


    IList<string> paliv = new List<string>();
    barvy.Add("Benzin");
    barvy.Add("Nafta");
    barvy.Add("LPG/CNG");
    barvy.Add("Elektrické");


}




<h2>
    <strong>Přidání automobilu:</strong>
</h2>

@Html.ValidationSummary()

@using (Html.BeginForm("AddAuto", "Database", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(Id => Model.Id)


    <div class="form-group">
        <label class="control-label col-sm-2">Značka:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x => x.Znacka.Id, new SelectList(ViewBag.Znacka, "Id", "Sznacka"), new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Model:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Model, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Model)


        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Max rychlost:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.MaxRychlost, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MaxRychlost)


        </div>
    </div>
    <div class="form-group ">
        <label class="control-label col-sm-2">Cena:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Cena, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Cena)


        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Najeto KM:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Najeto, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Najeto)


        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Palivo:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x => x.Palivo, new SelectList(paliv), new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Palivo)


        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Popis:</label>
        <div class="col-sm-10">

            @Html.TextAreaFor(x => x.Popis, new { @class = "form-control", rows = 10 })
            @Html.ValidationMessageFor(x => x.Popis)


        </div>
    </div>


    <div class="form-group ">
        <label class="control-label col-sm-2">Rok výroby:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.RokVyroby, new { @class = "form-control", rows = 10 })
            @Html.ValidationMessageFor(x => x.RokVyroby)


        </div>
    </div>



    <div class="form-group ">
        <label class="control-label col-sm-2">Typ karoserie:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.TypKaroserie, new { @class = "form-control", rows = 10 })
            @Html.ValidationMessageFor(x => x.TypKaroserie)


        </div>
    </div>



    <div class="form-group ">
        <label class="control-label col-sm-2">Objem motoru:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Objem, new { @class = "form-control", rows = 10 })
            @Html.ValidationMessageFor(x => x.Objem)


        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Výkon:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Vykon, new { @class = "form-control", rows = 10 })
            @Html.ValidationMessageFor(x => x.Vykon)

        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-sm-2">Barva:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x => x.Barva, new SelectList(barvy), new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Barva)

        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-sm-2">Země:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x => x.Zeme.Id, new SelectList(ViewBag.Zeme, "Id", "ZemePuvodu"), new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Faktura od firmy:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x => x.Faktura.Id, new SelectList(ViewBag.Faktura, "Id", "Firma"), new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Pobočka:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x => x.Pobocka.Id, new SelectList(ViewBag.Pobocka, "Id", "Nazev"), new { @class = "form-control" })

        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary" onclick="return confirm('Přejete si opravdu provést změny?')">Potvrdit</button>
        </div>
    </div>


}

Knihovna/Areas/Admin/Views/Database/AddPr.cshtml
@using DataAccess.Model
@model DataAccess.Model.Prislusenstvi

<h2>
    <strong>Přidání příslušenství:</strong>
</h2>

@Html.ValidationSummary()

@using (Html.BeginForm("AddPrislusenstvi", "Database", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(Id => Model.Id)
 
    <div class="form-group ">
        <label class="control-label col-sm-2">Název:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Nazev, new {@class="form-control"})
            @Html.ValidationMessageFor(x => x.Nazev)


        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Popis:</label>
        <div class="col-sm-10">
            @Html.TextAreaFor(x => x.Popis, new { @class = "form-control", rows = "10" })
            @Html.ValidationMessageFor(x => x.Popis)
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary" onclick="return confirm('Přejete si opravdu provést změny?')">Potvrdit</button>
        </div>
    </div>


}

Knihovna/Areas/Admin/Views/Database/DetailPr.cshtml
@model DataAccess.Model.Prislusenstvi

<p><strong>Identifikátor:</strong>
</p>
<p>
    @Model.Id
</p>
<p><strong>Název produktu:</strong></p>
<p>
    @Model.Nazev
</p>


<p><strong>Popis produktu:</strong>
    </p>
<p>
    @Model.Popis
</p>

Knihovna/Areas/Admin/Views/Database/DetailT.cshtml
@using DataAccess.Model
@model DataAccess.Model.TestovaciJizda

<p>
    <strong>Model a značka</strong>
</p>
<p>
    @Model.Auto.ModelAZnacka
</p>


<p><strong>Datum</strong></p>
<p>@Model.Datum.Day. @Model.Datum.Month. @Model.Datum.Year</p>

<p><strong>Délka</strong></p>
<p> @Model.Delka minut</p>

<p><strong>Registrovaný zákazník</strong></p>
<p>
    @Model.ZakaznikRegistrovany.Zakaznik.JmenoAPrijmeni
    <br>@Model.ZakaznikRegistrovany.Zakaznik.Email
    <br> @Model.ZakaznikRegistrovany.Zakaznik.Pohlavi
    <br> @Model.ZakaznikRegistrovany.Zakaznik.Psc.Psc
</p>

Knihovna/Areas/Admin/Views/Database/EditO.cshtml
@using DataAccess.Model
@model DataAccess.Model.Objednavka

<h2>
    <strong>Editace:</strong>
</h2>

@Html.ValidationSummary()

@using (Html.BeginForm("UpdateO", "Database", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(Id => Model.Id)
    @Html.HiddenFor(Datum => Model.Datum)


    <p>
        <strong>ID objednávky:</strong>
        @Model.Id
    </p>
    <p>
        <strong>Datum objednávky:</strong>
        @Model.Datum.Day. @Model.Datum.Month. @Model.Datum.Year
    </p>


    <div class="form-group ">
        <label class="control-label col-sm-2">Automobil:</label>
        <div class="col-sm-10">

            @if (Model.Auto != null)
            {
                @Html.DropDownList("Auto.Id", new SelectList(ViewBag.Auto, "Id", "ModelAZnacka", Model.Auto.Id), new { @class = "form-control" })
            }
            else
            {
                <p>Uživatel nemá ve své objednávce automobil</p>

            }

        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Zaměstnanec:</label>
        <div class="col-sm-10">

            @Html.DropDownList("Zamestnanec.Id", new SelectList(ViewBag.Zam, "Id", "JmenoAPrijmeni", Model.Zamestnanec.Id), new { @class = "form-control" })

        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-sm-2">Zákazník:</label>
        <div class="col-sm-10">

            @Html.DropDownList("Zakaznik.Id", new SelectList(ViewBag.Zak, "Id", "JmenoAPrijmeni", Model.Zakaznik.Id), new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Příslušenství:</label>
        <div class="col-sm-10">

            @if (Model.Prislusenstvi != null)
            {
                @Html.DropDownList("Prislusenstvi.Id", new SelectList(ViewBag.Pri, "Id", "Nazev", Model.Prislusenstvi.Id), new { @class = "form-control" })
            }
            else
            {
                <p>Uživatel nemá ve své objednávce příslušenství</p>
            }

        </div>
    </div>



    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary" onclick = "return confirm('Přejete si opravdu provést změny?')">Upravit</button>
        </div>
    </div>



}

Knihovna/Areas/Admin/Views/Database/EditP.cshtml
@using DataAccess.Model
@model DataAccess.Model.Pobocka

<h2>
    <strong>Editace:</strong>
</h2>

@Html.ValidationSummary()

@using (Html.BeginForm("UpdateP", "Database", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(Id => Model.Id)

    <div class="form-group ">
        <label class="control-label col-sm-2">Název:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Nazev, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Nazev)


        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Počet volných míst:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.PocetVolnychMist, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.PocetVolnychMist)


        </div>
    </div>

    <div class="form-group ">
        <label class="control-label col-sm-2">Interní číslo pobočky:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Cp, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Cp)


        </div>
    </div>
    <div class="form-group ">
        <label class="control-label col-sm-2">Celková kapacita:</label>
        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.CelkovaKapacita, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CelkovaKapacita)


        </div>
    </div>


    <div class="form-group ">
        <label class="control-label col-sm-2">Náleží do regionu:</label>
        <div class="col-sm-10">

            @Html.DropDownListFor(x =>x.Region.Id, new SelectList(ViewBag.Region, "Id", "Nazev", Model.Region.Id), new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Potvrdit</button>
        </div>
    </div>

}

Knihovna/Areas/Admin/Views/Database/EditPr.cshtml
@using DataAccess.Model
@model DataAccess.Model.Prislusenstvi

<h2>
    <strong>Editace:</strong>
</h2>

@Html.ValidationSummary()

@using (Html.BeginForm("UpdatePr", "Database", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(Id => Model.Id)
    <p>
        <strong>ID příslušenství:</strong>
        @Model.Id
    </p>


    <div class="form-group ">
        <label class="control-label col-sm-2">Název:</label>
        <div class="col-sm-10">

           @Html.TextBoxFor(x => x.Nazev, new {@class="form-control"})
            @Html.ValidationMessageFor(x => x.Nazev)


        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Popis:</label>
        <div class="col-sm-10">
            @Html.TextAreaFor(x => x.Popis, new { @class = "form-control", rows = "10" })
            @Html.ValidationMessageFor(x => x.Popis)
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary" onclick="return confirm('Přejete si opravdu provést změny?')">Upravit</button>
        </div>
    </div>



}

Knihovna/Areas/Admin/Views/Database/Testovaci.cshtml
@using DataAccess.Model
@model IList<TestovaciJizda>


@{
    ViewBag.Title = "Index";
}
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">

            </div>
        </div>
    </div>
</div>



<h1>Výpis testovacích jízd</h1>



<div class="clearfix"></div>

<table class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>Id</th>
        <th>Model</th>
        <th>Značka</th>
        <th>Datum</th>
        <th>Délka jízdy</th>
        <th>Zákazník</th>
        <th>Popis</th>
        <th>Akce</th>



    </tr>
    </thead>
    <tbody>
    @foreach (TestovaciJizda a in Model)
    {
        <tr>
            <td> @Ajax.ActionLink(a.Id.ToString(),"DetailT", new { id = a.Id }, new AjaxOptions() { UpdateTargetId = "modalContent", InsertionMode = InsertionMode.Replace, OnBegin = "openModalWindow"}, new{ @class="btn btn-primary container"})
            </td>
            <td>@a.Auto.Model</td>
            <td>@a.Auto.Znacka.Sznacka</td>
            <td>@a.Datum.Day/@a.Datum.Month/@a.Datum.Year</td>
            <td>@a.Delka minut</td>
            <td>@a.ZakaznikRegistrovany.Zakaznik.Jmeno @a.ZakaznikRegistrovany.Zakaznik.Prijmeni</td>
            <td>@a.Popis</td>

            <td>
                @Ajax.ActionLink("Editace", "EditT", new {a.Id}, new AjaxOptions() {UpdateTargetId = "modalContent", InsertionMode = InsertionMode.Replace, OnBegin = "openModalWindow"})
                @Html.ActionLink("Smazání", "DeleteT", "Database", new {id = a.Id}, new {onclick = "return confirm('prejete si opravdu smazat knihu " + a.Id + "');"})
            </td>

        </tr>
    }
    </tbody>
</table>

<script type="text/javascript">
    function openModalWindow() {
        $('#myModal').modal({
            show: true
        });
    }
</script>

Knihovna/Areas/Admin/Views/Database/Zakaznici.cshtml
@using DataAccess.Model
@model IList<Zakaznik>


@{
    ViewBag.Title = "Index";
}



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">

            </div>
        </div>
    </div>
</div>


<h1>Výpis zákazníků</h1>



<div class="clearfix"></div>

<table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Image</th>
            <th>Id</th>
            <th>Jméno</th>
            <th>Přijmení</th>
            <th>Email</th>
            <th>Opravneni</th>
            <th>Pohlavi</th>
            <th>Psč</th>
            <th>Akce</th>



        </tr>
    </thead>
    <tbody>
        @foreach (Zakaznik a in Model)
        {
            <tr>
                <td>  @{ Html.RenderAction("ImageRenderZak", "Database", new {a.Id}); }
                </td>
                <td>@a.Id</td>
                <td>@a.Jmeno</td>
                <td>@a.Prijmeni</td>
                <td>@a.Email</td>
                <td>@a.Opravneni.Sopravneni</td>
                <td>@a.Pohlavi</td>
                <td>@a.Psc.Psc</td>

                <td>
                    @Ajax.ActionLink("Editace", "EditZ", new { a.Id }, new AjaxOptions() { UpdateTargetId = "modalContent", InsertionMode = InsertionMode.Replace, OnBegin = "openModalWindow" })
                    @Html.ActionLink("Smazání", "DeleteZ", "Database", new { id = a.Id }, new { onclick = "return confirm('prejete si opravdu smazat knihu " + a.Email + "');" })
                </td>

            </tr>
        }
    </tbody>
</table>


<script type="text/javascript">
    function openModalWindow() {
        $('#myModal').modal({
            show: true
        });
    }
</script>