Knihovna/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using DataAccess.Dao;
using DataAccess.Model;

namespace Knihovna.Controllers
{
    public class CarsController : Controller
    {

        public ActionResult Index(int? page)
        {
            int itemsOnPage = 5;
            int pg = page.HasValue ? page.Value : 1;
            int totalCars;


            AutoDao autoDao = new AutoDao();
            IList<Auto> auta = autoDao.GetCarsPaged(itemsOnPage,pg,out totalCars);


            ViewBag.Pages = (int) Math.Ceiling((double) totalCars / (double) itemsOnPage);
            ViewBag.CurrentPage = pg;

            ImageAutoDao ImageDao = new ImageAutoDao();
            IList<ImageAuto> image = ImageDao.GetAll();

            ViewBag.Photo = image;
            return View(auta);
        }

        public ActionResult Detail(int id)
        {
            AutoDao autoDao = new AutoDao();
            Auto a = autoDao.GetById(id);


            ImageAutoDao ImageDao = new ImageAutoDao();
            IList<ImageAuto> image = ImageDao.ImageAuto(id);
            ViewBag.Photo = image;
            return View(a);
        }


        public ActionResult Search(string phrase)
        {
            AutoDao autoDao = new AutoDao();
            IList<Auto> auta = autoDao.SearchCars(phrase);
            
            return View("Index", auta);
        }

        public ActionResult ImageRender(int id)
        {

            ImageAutoDao imageAutoDao = new ImageAutoDao();

            IList<ImageAuto> imageAuto = imageAutoDao.HeadImageAuto(id);

            if (imageAuto.Count == 0)
            {
                imageAuto = imageAutoDao.HeadImageAuto(1);
            }

            return View(imageAuto);
        }
        [Authorize]
        public ActionResult Testovat(int id)
        {

            


            ZakaznikDao zakaznikDao = new ZakaznikDao();
            Zakaznik zakaznik = zakaznikDao.GetByLogin(User.Identity.Name);
            ViewBag.Zakazanik = zakaznik;

            AutoDao autoDao = new AutoDao();
            Auto a = autoDao.GetById(id);
            ImageAutoDao imageDao = new ImageAutoDao();
            IList<ImageAuto> image = imageDao.HeadImageAuto(id);
            ViewBag.Image = image;


            ZakaznikRegistrovanyDao registrovanyDao = new ZakaznikRegistrovanyDao();
            ZakaznikRegistrovany registrovany = registrovanyDao.GetByZakaznik(zakaznik.Id);
            if (registrovany == null)
            {registrovany = new ZakaznikRegistrovany();
            }

            ViewBag.tel = registrovany.Telefon;
            ViewBag.ulice = registrovany.Ulice;
            ViewBag.mesto = registrovany.Mesto;

            return View(a);

        }
        [Authorize]
        public ActionResult Objednat(int id)
        {

            ZakaznikDao zakaznikDao = new ZakaznikDao();
            Zakaznik zakaznik = zakaznikDao.GetByLogin(User.Identity.Name);
            ViewBag.Zakazanik = zakaznik;


            AutoDao autoDao = new AutoDao();
            Auto a = autoDao.GetById(id);
            ImageAutoDao imageDao = new ImageAutoDao();
            IList<ImageAuto> image = imageDao.HeadImageAuto(id);
            ViewBag.Image = image;

            return View(a);

        }
        [Authorize]
        public ActionResult ObjednatAuto(int id)
        {
            DateTime date = DateTime.Now;

            AutoDao autoDao = new AutoDao();
            Auto auto = autoDao.GetById(id);

            ZakaznikDao zakaznikDao = new ZakaznikDao();
            Zakaznik zakaznik = zakaznikDao.GetByLogin(User.Identity.Name);

            ZamestnanecDao zamestnanecDao = new ZamestnanecDao();
            IList<Zamestnanec> zamestnanec = zamestnanecDao.GetByPobocka(auto.Pobocka.Id);
            Zamestnanec obchodnik = zamestnanec[new Random().Next(zamestnanec.Count)];

            PrislusenstviDao prislusenstviDao = new PrislusenstviDao();
            IList<Prislusenstvi> prislusenstvi = prislusenstviDao.GetAll();
            Prislusenstvi prislus = prislusenstvi[new Random().Next(prislusenstvi.Count)];

            ObjednavkaDao objednavkaDao = new ObjednavkaDao();
            Objednavka objednavka = new Objednavka();

            objednavka.Auto = auto;
            objednavka.Zakaznik = zakaznik;
            objednavka.Datum = date;
            objednavka.Zamestnanec = obchodnik;
            objednavka.Prislusenstvi = prislus;

            objednavkaDao.Create(objednavka);
            TempData["message-success"] = "Objednávka byla dokončena";

            return RedirectToAction("Index");
        }
        public ActionResult TestovatAuto(string telefon, string ulice, string mesto,int id)
        {
            ZakaznikDao zakaznikDao = new ZakaznikDao();
            Zakaznik zakaznik = zakaznikDao.GetByLogin(User.Identity.Name);

            ZakaznikRegistrovanyDao registrovanyDao = new ZakaznikRegistrovanyDao();
            ZakaznikRegistrovany registrovany = registrovanyDao.GetByZakaznik(zakaznik.Id);
            if (registrovany == null)
            {
                registrovany = new ZakaznikRegistrovany();
                registrovany.Zakaznik = zakaznik;
                registrovany.Telefon = telefon;
                registrovany.Ulice = ulice;
                registrovany.Mesto = mesto;
                registrovany.PocetPixelFreeBodu = 0;

                registrovanyDao.Create(registrovany);
            }
            else
            {
                registrovany.Telefon = telefon;
                registrovany.Ulice = ulice;
                registrovany.Mesto = mesto;
                registrovany.PocetPixelFreeBodu = registrovany.PocetPixelFreeBodu + 10;
                registrovanyDao.Update(registrovany);

            }


            AutoDao autoDao = new AutoDao();
            Auto auto = autoDao.GetById(id);
            TestovaciJizdaDao testovaciDao = new TestovaciJizdaDao();
            TestovaciJizda testovaciJizda = new TestovaciJizda();


            ZamestnanecDao zamestnanecDao = new ZamestnanecDao();
            IList<Zamestnanec> zamestnanec = zamestnanecDao.GetByPobocka(auto.Pobocka.Id);
            Zamestnanec obchodnik = zamestnanec[new Random().Next(zamestnanec.Count)];




            testovaciJizda.Auto = auto;
            testovaciJizda.Datum = DateTime.Now;
            testovaciJizda.Zamestnanec = obchodnik;
            testovaciJizda.ZakaznikRegistrovany = registrovany;
            testovaciJizda.Delka = 10;
            testovaciJizda.Popis = "platna";
            testovaciDao.Create(testovaciJizda);

            TempData["message-success"] = "Objednávka byla dokončena";
            return RedirectToAction("Index");
        }
    }
}

Knihovna/Views/Cars/Detail.cshtml
@using DataAccess.Model
@model  Auto

<div class="container">


    <div class="wrapper row">
        <div class="preview mb-2">

            <div class="preview-pic tab-content">

                @{
                    IList<String> img = new List<string>();
                    String first = "~/img/one.jpg";

                    if (ViewBag.Photo.Count != null)
                    {
                        foreach (var photo in ViewBag.Photo as List<ImageAuto>)
                        {

                            if (photo.SIsFirst)
                            {
                                first = "~/img/img_cars/" + photo.ImageName;
                            }
                            else
                            {
                                img.Add("~/img/img_cars/" + photo.ImageName);

                            }

                        }

                    }


                }


                <div class="tab-pane active" id="pic-1"><img src="@Url.Content(first)" /></div>
                @switch (img.Count)
                {
                    case 1:
                        <div class="tab-pane" id="pic-2"><img src="@Url.Content(img[0])" /></div>
                        <div class="tab-pane" id="pic-3"><img src="@Url.Content("~/img/one.jpg")" /></div>
                        <div class="tab-pane" id="pic-4"><img src="@Url.Content("~/img/one.jpg")" /></div>
                        <div class="tab-pane" id="pic-5"><img src="@Url.Content("~/img/one.jpg")" /></div>

                        break;

                    case 2:
                        <div class="tab-pane" id="pic-2"><img src="@Url.Content(img[0])" /></div>
                        <div class="tab-pane" id="pic-3"><img src="@Url.Content(img[1])" /></div>
                        <div class="tab-pane" id="pic-4"><img src="@Url.Content("~/img/one.jpg")" /></div>
                        <div class="tab-pane" id="pic-5"><img src="@Url.Content("~/img/one.jpg")" /></div>break;

                    case 3:
                        <div class="tab-pane" id="pic-2"><img src="@Url.Content(img[0])" /></div>
                        <div class="tab-pane" id="pic-3"><img src="@Url.Content(img[1])" /></div>
                        <div class="tab-pane" id="pic-4"><img src="@Url.Content(img[2])" /></div>
                        <div class="tab-pane" id="pic-5"><img src="@Url.Content("~/img/one.jpg")" /></div>break;
                    case 4:
                        <div class="tab-pane" id="pic-2"><img src="@Url.Content(img[0])" /></div>
                        <div class="tab-pane" id="pic-3"><img src="@Url.Content(img[1])" /></div>
                        <div class="tab-pane" id="pic-4"><img src="@Url.Content(img[2])" /></div>
                        <div class="tab-pane" id="pic-5"><img src="@Url.Content(img[3])" /></div>break;
                    default:
                        <div class="tab-pane" id="pic-2"><img src="@Url.Content("~/img/one.jpg")" /></div>
                        <div class="tab-pane" id="pic-3"><img src="@Url.Content("~/img/one.jpg")" /></div>
                        <div class="tab-pane" id="pic-4"><img src="@Url.Content("~/img/one.jpg")" /></div>
                        <div class="tab-pane" id="pic-5"><img src="@Url.Content("~/img/one.jpg")" /></div>
                        break;
                }



                <ul class="preview-thumbnail nav nav-tabs">

                    <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="@Url.Content(first)" /></a></li>
                    @switch (img.Count)
                    {
                        case 1:
                            <li><a data-target="#pic-2" data-toggle="tab"><img src="@Url.Content(img[0])" /></a></li>
                            <li><a data-target="#pic-3" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>
                            <li><a data-target="#pic-4" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>
                            <li><a data-target="#pic-5" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>

                            break;

                        case 2:
                            <li><a data-target="#pic-2" data-toggle="tab"><img src="@Url.Content(img[0])" /></a></li>
                            <li><a data-target="#pic-3" data-toggle="tab"><img src="@Url.Content(img[1])" /></a></li>
                            <li><a data-target="#pic-4" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>
                            <li><a data-target="#pic-5" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>break;

                        case 3:
                            <li><a data-target="#pic-2" data-toggle="tab"><img src="@Url.Content(img[0])" /></a></li>
                            <li><a data-target="#pic-3" data-toggle="tab"><img src="@Url.Content(img[1])" /></a></li>
                            <li><a data-target="#pic-4" data-toggle="tab"><img src="@Url.Content(img[2])" /></a></li>
                            <li><a data-target="#pic-5" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>break;
                        case 4:
                            <li><a data-target="#pic-2" data-toggle="tab"><img src="@Url.Content(img[0])" /></a></li>
                            <li><a data-target="#pic-3" data-toggle="tab"><img src="@Url.Content(img[1])" /></a></li>
                            <li><a data-target="#pic-4" data-toggle="tab"><img src="@Url.Content(img[2])" /></a></li>
                            <li><a data-target="#pic-5" data-toggle="tab"><img src="@Url.Content(img[3])" /></a></li>break;
                        default:
                            <li><a data-target="#pic-2" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>
                            <li><a data-target="#pic-3" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>
                            <li><a data-target="#pic-4" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>
                            <li><a data-target="#pic-5" data-toggle="tab"><img src="@Url.Content("~/img/one.jpg")" /></a></li>
                            break;
                    }



                </ul>
            </div>
        </div>
        <div class="details">
            <h3 class="product-title">@Model.Znacka.Sznacka @Model.Model</h3>


            <h4 class="price">Cena: <span>@Model.Cena.ToString("C0")</span></h4>


            <!-- Details of the car -->
            <div class="row">
                <div class="col">
                    <p><strong>Rok výroby:</strong> @Model.RokVyroby.Day/@Model.RokVyroby.Month/@Model.RokVyroby.Year</p>
                    <p><strong>Typ karoserie:</strong> @Model.TypKaroserie </p>
                    <p><strong>Max. rychlost:</strong> @Model.MaxRychlost <strong>km/h</strong></p>
                    <p><strong>Tachometr:</strong> @Model.Najeto.ToString("N0") <strong>km</strong></p>
                </div> <div class="col">
                    <p><strong>Objem:</strong> @Model.Objem</p>
                    <p><strong>Výkon:</strong> @Model.Vykon <strong>kW</strong></p>
                    <p><strong>Palivo:</strong> @Model.Palivo </p>
                    <p><strong>Země původu:</strong> @Model.Zeme.ZemePuvodu</p>
                </div>
            </div>
            <p>
                <strong>Barva:</strong>
                <span class="rounded color @Model.Barva" data-toggle="tooltip"></span>
            </p>
            <!-- End details-->

            <p>@Model.Popis</p>
            
            
          @if (User.Identity.IsAuthenticated)
          {
              <div class="row justify-content-between">
                  <div class="col-lg-4">
                      <a href="@Url.Action("Testovat", new{ Model.Id})" class="add-to-cart btn btn-default">Objednat si testovací jízdu</a>
                  </div>
                  <div class="col-lg-4">
                      <a href="@Url.Action("Objednat", new { Model.Id})" class="add-to-cart btn btn-default">Objednat si automobil</a>
                  </div>
              </div>

          }
    
       
            
            
            
            

        </div>
    </div>


</div>

Knihovna/Views/Cars/ImageRender.cshtml
@using DataAccess.Model
@model IList<ImageAuto>

@{
    Layout = null;
  
}

@foreach (ImageAuto i in Model)
{
    if (!string.IsNullOrEmpty(i.ImageName))
    {
        <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="@Url.Content("~/img/img_cars/" + i.ImageName)" alt="fotka" width="100%" />
    }

}

Knihovna/Views/Cars/Index.cshtml
@using DataAccess.Model
@model IList<Auto>

@if (TempData["message-success"] != null)
{
    <div class="alert alert-success">
        <strong>Výborně!</strong> Objednávka byla úspěšně odeslána.
    </div>
}
@if (TempData["error"] != null)
{
    <div class="alert alert-danger">
        <strong>Jejda!</strong> Objednávka nebyla odeslána, zkontrolujte vaše údaje.
    </div>
}


<div class="row justify-content-between">
    <div class="col-6">
        <h1>Nabídka automobilů</h1>

    </div>
    <div class="col-4">
        @if (ViewBag.Pages != null)
        {
            <div class="float-right">
               <a> Aktuální stránka: </a>
                <ul class="pagination">

                    @for (int i = 1; i <= ViewBag.Pages; i++)
                    {
                        <li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")"><a class="page-link" href="@Url.Action("Index", "Cars", new {page = i})">@i</a></li>
                    }

                </ul>

            </div>
       
        }
    </div>

</div>






@foreach (Auto a in Model)
{

    <section class="page-section">
        <div class="container">
            <div class="product-item">
                <div class="product-item-title d-flex">

                    <div class="bg-faded p-5 d-flex ml-auto rounded">
                        <h2 class="section-heading mb-0">
                            <span class="section-heading-upper">@a.Znacka.Sznacka </span>
                            <span class="section-heading-upper ">@a.Model</span>
                        </h2>
                    </div>
                </div>                    @{Html.RenderAction("ImageRender", "Cars", new { a.Id });}

                <div class="product-item-description d-flex mr-auto">

                    <div class="bg-faded p-3 rounded">
                        <p>
                            @a.Popis.Substring(0, 100) ...
                        </p>
                        <p class="font-weight-bold float-left">Cena:  <span class="font-italic"> @a.Cena.ToString("C0")</span></p>
                        <p class="font-weight-bold text-right">Dostupnost:  <span style="color:green"class="font-bold"> Ihned k odběru</span></p>

                        <p>
                            <div class="clearfix"></div>
                            <a class="btn btn-primary float-lg-right" href="@Url.Action("Detail", "Cars", new {id = a.Id})">Více informací o automobilu</a>

                        </p>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <hr>







}
@if (ViewBag.Pages != null)
{
    <div class="container">
        <div class="float-lg-right">
            <a>Stránka:</a>
            <ul class="pagination">
                @for (int i = 1; i <= ViewBag.Pages; i++)
                {
                    <li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")"><a class="page-link" href="@Url.Action("Index","Cars", new{page=i})">@i</a></li>
                }
            </ul>

        </div>
    </div>
    <div class="pb-5"></div>

}

Knihovna/Views/Cars/Objednat.cshtml
@using DataAccess.Model
@model Auto

@{
    ViewBag.Title = "title";
}

<h1>Závazná objednávka automobilu @Model.ModelAZnacka</h1>
<hr>
@foreach (ImageAuto i in ViewBag.Image)
{
    if (!string.IsNullOrEmpty(i.ImageName))
    {
        <img src="@Url.Content("~/img/img_cars/" + i.ImageName)" width=100% />
    }


}
<hr>

<div class="row">
    <div class="col">
        <p><strong>Rok výroby:</strong> @Model.RokVyroby.Day/@Model.RokVyroby.Month/@Model.RokVyroby.Year</p>
        <p><strong>Typ karoserie:</strong> @Model.TypKaroserie </p>
        <p><strong>Max. rychlost:</strong> @Model.MaxRychlost <strong>km/h</strong></p>
        <p><strong>Tachometr:</strong> @Model.Najeto.ToString("N0") <strong>km</strong></p>
    </div> <div class="col">
        <p><strong>Objem:</strong> @Model.Objem L</p>
        <p><strong>Výkon:</strong> @Model.Vykon <strong>kW</strong></p>
        <p><strong>Palivo:</strong> @Model.Palivo </p>
        <p><strong>Země původu:</strong> @Model.Zeme.ZemePuvodu</p>
    </div>
</div>

<hr>
<h2>Uživatel:</h2>

<div class="row">

    <div class="col">
        <p>
            <strong>Jméno a přijmení </strong>@ViewBag.Zakazanik.JmenoAPrijmeni
        </p>
        <p>
            <strong>Email </strong>@ViewBag.Zakazanik.Email
        </p>
        <p>
            <strong>Pohlaví </strong>@ViewBag.Zakazanik.Pohlavi
        </p>
      
        <p>
            <strong>PSČ </strong>@ViewBag.Zakazanik.Psc.Psc
        </p>
        <p>
            <strong>Stát </strong>Česká republika
        </p>
    </div>

    <div class="col align-self-end ">
        <div class="">
            <a href="@Url.Action("ObjednatAuto", new{ Model.Id})" class="add-to-cart btn btn-default">Závazně objednávám</a>
        </div>
    </div>

</div>

Knihovna/Views/Cars/Testovat.cshtml
@using DataAccess.Model
@model Auto

@{
    ViewBag.Title = "title";
}

<h1>Testovací projížďka automobilu @Model.ModelAZnacka</h1>
<hr>
@foreach (ImageAuto i in ViewBag.Image)
{
    if (!string.IsNullOrEmpty(i.ImageName))
    {
        <img src="@Url.Content("~/img/img_cars/" + i.ImageName)" width=100% />
    }


}


<div class="row">
    <div class="col">
        <p><strong>Rok výroby:</strong> @Model.RokVyroby.Day/@Model.RokVyroby.Month/@Model.RokVyroby.Year</p>
        <p><strong>Typ karoserie:</strong> @Model.TypKaroserie </p>
        <p><strong>Max. rychlost:</strong> @Model.MaxRychlost <strong>km/h</strong></p>
        <p><strong>Tachometr:</strong> @Model.Najeto.ToString("N0") <strong>km</strong></p>
    </div> <div class="col">
        <p><strong>Objem:</strong> @Model.Objem</p>
        <p><strong>Výkon:</strong> @Model.Vykon <strong>kW</strong></p>
        <p><strong>Palivo:</strong> @Model.Palivo </p>
        <p><strong>Země původu:</strong> @Model.Zeme.ZemePuvodu</p>
    </div>
</div>

<hr>
<h2>Uživatel:</h2>

<div class="row">

    <div class="col">
        <p>
            <strong>Jméno a přijmení: </strong>@ViewBag.Zakazanik.JmenoAPrijmeni
        </p>
        <p>
            <strong>Email: </strong>@ViewBag.Zakazanik.Email
        </p>
        <p>
            <strong>Pohlaví: </strong>@ViewBag.Zakazanik.Pohlavi
        </p>
 
        <p>
            <strong>PSČ: </strong>@ViewBag.Zakazanik.Psc.Psc
        </p>
        <p>
            <strong>Stát: </strong>Česká republika
        </p>
    </div>

    <div class="col align-self-end ">
        
        <p>
            <strong>Dodatečné informace</strong>
        </p>
        @Html.ValidationSummary()

        @using (Html.BeginForm("TestovatAuto", "Cars", FormMethod.Post, new {@class = "form-horizontal"}))
        {

            @Html.Hidden("id", Model.Id)

            <div class="form-group ">
                <label class="control-label">Telefonní číslo:</label>
                <div class="col-sm-10">

                    @Html.TextBox("telefon", (string) ViewBag.tel)


                </div>
            </div>

            <div class="form-group ">
                <label class="control-label">Ulice a číslo domu:</label>
                <div class="col-sm-10">

                    @Html.TextBox("ulice", (string) ViewBag.ulice)


                </div>
            </div>
            <div class="form-group ">
                <label class="control-label">Město:</label>
                <div class="col-sm-10">

                    @Html.TextBox("mesto", (string) ViewBag.mesto)


                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="add-to-cart btn btn-default">Závazně objednávám testovací jízdu</button>
                </div>
            </div>

        }


    </div>

</div>